version: '3.8'

services:
  sql-translator:
    container_name: sql-translator
    image: sql-translator:0.0.6
    hostname: sql-translator
    ports:
      - "8080:8080"

  vue-frontend:
    container_name: vue-frontend
    image: vue-frontend:git2
    environment:
      MAIN_HEADER_MSG: "✨ Welcome!"
      MAIN_HEADER_HYPERLINK: "https://example.com"
      RUN_BUTTON_HYPERLINK:  "https://example.com"
    ports:
      - "80:80"
    depends_on:
      - sql-translator
