apiVersion: v1
kind: Service
metadata:
  name: vue-frontend
spec:
  type: NodePort
  selector:
    app: vue-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.vueFrontend.service.port }}
